name: deploy-lambda-action
description: Deploy a Lambda function with container image

inputs:
  function-name:
    description: Name of the function
    required: true
  image-uri:
    description: URI of the container image
    required: false
  zip-path:
    description: Path to the archive
    required: false
  alias-name:
    description: Name of the function alias (optional)
    required: false
  alias-description:
    description: Description of the function alias (optional)
    required: false
    default: ref=${{ github.ref }},sha=${{ github.sha }}

outputs:
  function-version:
    description: Published version
  function-version-arn:
    description: ARN of published version
  function-alias-arn:
    description: ARN of alias

runs:
  using: 'node20'
  main: 'dist/index.js'
